export const projects = [
  {
    slug: "Citioyen",
    title: "Citioyen",
    tagline: "AI-powered civic issue reporting platform",
    tech: ["React 19", "Express 5", "TypeScript", "PostgreSQL", "Gemini API", "Docker", "GCP"],
    role: "Full-Stack Developer",
    highlights: [
      "Built an AI-powered civic issue reporting platform end-to-end, integrating the Gemini API for issue categorization, severity scoring, and resolution verification with human override.",
      "Implemented pgvector (HNSW) duplicate detection and deployed a containerized full stack on Google Cloud Run with Cloud SQL and OAuth 2.0 authentication.",
    ],
    github: "https://github.com/Manav-Sonawane/citioyen",
    live: null,
  },
  {
    slug: "MAArK",
    title: "MAArK",
    tagline: "Privacy-First Search Engine and Browser",
    tech: ["Java", "Maven", "JavaFX", "Electron IPC"],
    role: "Backend Developer",
    highlights: [
      "Led backend development of a privacy-first desktop browser using Java and Electron IPC.",
      "Architected triple-tier IP masking, per-tab session isolation, and anti-fingerprinting.",
      "Added breach detection via HaveIBeenPwned.",
    ],
    github: "https://github.com/Manav-Sonawane/MAArK",
    live: null,
  },
  {
    slug: "Codered-IO",
    title: "Codered IO",
    tagline: "Browser-based arcade platform with 2D and 3D games",
    tech: ["React", "Three.js", "Socket.io", "Express.js", "MongoDB"],
    role: "Full-Stack Developer",
    highlights: [
      "Built a browser-based arcade platform with four 2D/3D games at the Devhacks hackathon.",
      "Implemented real-time multiplayer sync using Socket.io.",
      "Designed 3D game rendering and interactions using Three.js.",
    ],
    github: "https://github.com/Manav-Sonawane/CodeRed.io",
    live: "https://codered-io.onrender.com",
  },
  {
    slug: "SeaSarathi",
    title: "SeaSarathi",
    tagline: "Marine intelligence platform — agentic AI fishing advisory for Indian coastal fishermen (FastAPI, LangGraph, Claude 3.5 Sonnet)",
    tech: ["FastAPI", "LangGraph", "Claude 3.5 Sonnet", "GeoPandas"],
    role: "Full-Stack Developer",
    highlights: [
      "Built an agentic AI fishing-advisory app for Indian coastal fishermen, orchestrating safety and fishing-zone recommendations via LangGraph and Claude 3.5 Sonnet over live and historical marine data.",
    ],
    github: "https://github.com/Manav-Sonawane/SeaSarathi",
    live: null,
  },
  {
    slug: "PlayStation-UI-Revamp",
    title: "PlayStation UI Revamp",
    tagline: "Social-first gaming dashboard built in a 5-hour hackathon sprint — MockUp'26, Top 8 (Team CodeSI)",
    tech: ["React", "Vite", "Tailwind CSS", "Framer Motion", "GSAP"],
    role: "Frontend Developer",
    highlights: [
      "Reimagined a streaming-platform-style UI as a social-first gaming dashboard in a 5-hour hackathon sprint — MockUp'26, Top 8 finish (Team CodeSI).",
    ],
    github: "https://github.com/Manav-Sonawane/Playstation-Revamp",
    live: null,
  },
  {
    slug: "CareerForge-AI",
    title: "CareerForge AI",
    tagline: "NLP-based resume analyzer (PyTesseract OCR + Gemini API) for skill-gap analysis and career recommendations",
    tech: ["Python", "Flask", "Gemini API", "NLP"],
    role: "Full-Stack Developer",
    highlights: [
      "Built an NLP-based resume parser (PyTesseract OCR + Gemini API) for skill-gap analysis and career recommendations.",
    ],
    github: "https://github.com/Manav-Sonawane/CareerForge_AI",
    live: null,
  },
  {
    slug: "BookMySeat",
    title: "BookMySeat",
    tagline: "Movie ticket booking platform like BookMyShow",
    tech: ["Django", "Python", "PostgreSQL", "Redis"],
    role: "Full-Stack Developer",
    highlights: [
      "Implemented concurrency-safe seat reservation, Redis-backed session caching, JWT/OAuth authentication, payment gateway integration, and automated email confirmations.",
      "Built an admin panel with analytics dashboards and movie management, with Cron-scheduled jobs for routine data upkeep.",
    ],
    github: "https://github.com/Manav-Sonawane/BookMySeat",
    live: null,
  },
];
